version: '3.7'

services:
  backend:
    build: ./backend   # Path to your backend Dockerfile
    ports:
      - "8080:8080"   # Map container port 8080 to host port 8080
    environment:
      - PORT=8080     # Set the port environment variable
      - MONGODB_URL= mongodb+srv://efacwebapp:oALcnx4oKRNow7qv@cluster0.9gqhinc.mongodb.net/efacwebapp1_db?retryWrites=true&w=majority  # MongoDB connection URL
    depends_on:
      - mongo         # Depends on the mongo service
    links:
      - mongo         # Link with the mongo service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    volumes:
      - mongodb_data:/data/db  # Mount volume for MongoDB data

  frontend:
    build: ./frontend  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"   # Map container port 3000 to host port 3000
    depends_on:
      - backend       # Depends on the backend service

volumes:
  mongodb_data:
